### PR TITLE
Add sponsor name + Sandia logo

### LINKED ISSUE #69: Add sponsors name
@TanuMalik would like to include name of the sponsors in addition to their logos: 

Here is a full list: Inria, Rennes Metropole, Region Bretagne, Université de Rennes and Sandia National Laboratory.

@msimonin would you be willing to create a PR for this?

### LINKED ISSUE #74: Add sandia's logo
We need to add the logo of sandia to the website as one of our sponsors. @gflofst: do you have a file that we can use?

### PR DESCRIPTION
**Pull request by msimonin**
Fix #69
Fix #74

### CODE REVIEW

**Comment by cmaumet** [comment]
Thank you @msimonin! @carlosmalt: let us know if this is good to merge.

**Comment by cmaumet** [comment]
@msimonin -- I think the sponsor page (https://github.com/acm-rep/2024/blob/main/content/sponsor/index.md) also needs to be updated.

**Comment by msimonin** [comment]
I've updated the sponsor page the easy way to not repeat sponsor list there (they are already in the frontpage ! )

**Review by carlosmalt — CHANGES_REQUESTED** [review]
Thanks @msimonin — please add the Sandia logo (either in the same local directory of the markdown that references it or in `/assets/media`). It can be either a png or a jpeg file. The various sizing and resolution alternatives are all generated by the Hugo website rendering. So a high resolution logo would be best. 

It would be nice to center the logos. This can be done with the usual `<center>…</center>` html markup.

**Comment by msimonin** [comment]
added the missing image,
didn't centered the logo, will come back on this if time allows (could you merge it in the current state if that's ok from your side)

**Comment by msimonin** [comment]
Centered the sponsor list (I used a good old table for this ! )

**Review by carlosmalt — APPROVED** [review]
Great - Thanks @msimonin - I will merge now.

**Pull request merged**
